name: TEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Auto_Deploy:
    runs-on: ubuntu-latest

    steps:
#     CI
#     - uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - name: npm setting
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
    - uses: actions/checkout@v3
    - run: echo `
          PW=#test1234;
          sshpass -p $PW ssh -l test test.gractor.com -p 22022
        ` >> connection.sh 
    - run: connections.sh && docker ps
